DCI-683: Add inventory check
Runs ansible-inventory on host files, detect if there any warnings/errors on
stderr.
In that case, the script exits and display the warnings/errors.

Change-Id: Ibef4dd4823dfe39ddfb223bfa7319783e5cbe305

diff --git a/dci-openshift-agent-ctl b/dci-openshift-agent-ctl
--- a/dci-openshift-agent-ctl
+++ b/dci-openshift-agent-ctl
@@ -98,6 +98,29 @@ function interrupt() {
 
 trap interrupt INT TERM
 
+function check_inventory() {
+    # if ansible-inventory not in $PATH, skip inventory check
+    if ! command -v ansible-inventory; then
+	echo "SKIP: inventory check, ansible-inventory not in PATH"
+	return 0
+    fi
+
+    # retrieve stderr output
+    stderr=$(ansible-inventory --list $1  2>&1 1>/dev/null)
+    stderr_orig="$stderr"
+    # remove leading whitespace characters
+    stderr="${stderr#${stderr%%[![:space:]]*}}"
+    # remove trailing whitespace characters
+    stderr="${stderr%${stderr##*[![:space:]]}}"
+
+    if [[ -n $stderr ]]; then
+	echo "Inventory error\nERROR: $stderr_orig"
+	exit 1
+    else
+	echo "Inventory: no syntax issue detected at this stage"
+    fi
+}
+
 if [ -r /etc/dci-openshift-agent/config ]; then
     . /etc/dci-openshift-agent/config
 fi
@@ -191,6 +214,9 @@ if [ "$start" -eq 1 ]; then
         export ANSIBLE_CONFIG=$DIR/dev-ansible.cfg
         DCI_OPENSHIFT_AGENT_DIR=${DCI_OPENSHIFT_AGENT_DIR:-$DIR}
     fi
+
+    # run check_inventory on all host files
+    check_inventory $host_args
 
     OUTPUT_DIR="$(mktemp -d /tmp/dci-openshift-agent.XXXXX)"
     cd "${OUTPUT_DIR}" || exit 1
