WIP: Initial work on integrating Assisted Installer
This is the initial work to integrate the assisted installer into the
DCI agent.

Test-Hints: no-check
Test-Hints: assisted

Change-Id: I4fe57a54252cc058afe729c382e8de4df223f052

diff --git a/dci-check-change b/dci-check-change
--- a/dci-check-change
+++ b/dci-check-change
@@ -156,7 +156,7 @@ if [ -d $DIR ]; then
      fi
 fi
 
-trap cleanup 0
+#trap cleanup 0
 
 mkdir -p $DIR
 cd $DIR
